---
- hosts: cns
  gather_facts: yes
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  - setup-custom-domain-names
  - instance-groups
  - package-repos
  - vmware-guest-setup
  - cloud-provider-setup
  - docker-storage-setup
  - openshift-volume-quota
  - gluster-ports

# 'openshift_node_groups' var started being required since OCP3.10
- hosts: allnodes
  gather_facts: no
  become: no
  tasks:
  - set_fact:
      openshift_crio_docker_gc_node_selector:
        runtime: crio
      openshift_node_groups:
      - name: node-config-master
        labels:
        - 'node-role.kubernetes.io/master=true'
        - 'role=master'
        edits: []
      - name: node-config-master-crio
        labels:
        - 'node-role.kubernetes.io/master=true'
        - 'role=master'
        - 'runtime=cri-o'
        edits:
        - key: kubeletArguments.container-runtime
          value: ["remote"]
        - key: kubeletArguments.container-runtime-endpoint
          value: ["/var/run/crio/crio.sock"]
        - key: kubeletArguments.image-service-endpoint
          value: ["/var/run/crio/crio.sock"]
        - key: kubeletArguments.runtime-request-timeout
          value: ["10m"]
      - name: node-config-compute
        labels:
        - 'node-role.kubernetes.io/compute=true'
        - 'node-role.kubernetes.io/infra=true'
        - 'role=compute'
        edits: []
      - name: node-config-compute-crio
        labels:
        - 'node-role.kubernetes.io/compute=true'
        - 'node-role.kubernetes.io/infra=true'
        - 'role=compute'
        - 'runtime=cri-o'
        edits:
        - key: kubeletArguments.container-runtime
          value: ["remote"]
        - key: kubeletArguments.container-runtime-endpoint
          value: ["/var/run/crio/crio.sock"]
        - key: kubeletArguments.image-service-endpoint
          value: ["/var/run/crio/crio.sock"]
        - key: kubeletArguments.runtime-request-timeout
          value: ["10m"]
      - name: node-config-storage
        labels:
        - 'node-role.kubernetes.io/storage=true'
        - 'role=storage'
        edits: []
      - name: node-config-storage-crio
        labels:
        - 'node-role.kubernetes.io/storage=true'
        - 'role=storage'
        - 'runtime=cri-o'
        edits:
        - key: kubeletArguments.container-runtime
          value: ["remote"]
        - key: kubeletArguments.container-runtime-endpoint
          value: ["/var/run/crio/crio.sock"]
        - key: kubeletArguments.image-service-endpoint
          value: ["/var/run/crio/crio.sock"]
        - key: kubeletArguments.runtime-request-timeout
          value: ["10m"]

- include: add-node-prerequisite.yaml
  when: openshift_vers in ['v3_6', 'v3_7']

- include: "{{ (openshift_vers in ['v3_6', 'v3_7']) | ternary(
      'noop.yaml',
      lookup('env', 'VIRTUAL_ENV') +
          '/usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml'
  ) }} hosts=new_nodes"
  when: openshift_vers not in ['v3_6', 'v3_7']

- include: "{{ (openshift_vers in ['v3_6', 'v3_7']) | ternary(
      'noop.yaml',
      lookup('env', 'VIRTUAL_ENV') +
          '/usr/share/ansible/openshift-ansible/playbooks/init/main.yml'
  ) }} hosts=new_nodes"
  when: openshift_vers not in ['v3_6', 'v3_7']

- name: Map domain names and IP addresses of old and new nodes to each other
  hosts: master, compute, crs
  vars_files:
    - vars/main.yaml
  roles:
    - setup-custom-domain-names

- hosts: allnodes
  gather_facts: no
  become: no
  tasks:
  - name: Make sure dnsmasq is running, enabled and restarted
    service: name=dnsmasq state=restarted enabled=yes

- hosts: localhost
  gather_facts: no
  become: no
  roles:
  - yum-update-and-reboot

- hosts: single_master
  gather_facts: no
  tasks:
  - name: Make sure oc client is responsive
    command: oc status
    retries: 120
    delay: 5
    register: oc_status_result
    until: oc_status_result is succeeded
