---
# create rhsm_user, rhsm_password, rhsm_subscription_pool and
# rhsm_server for functionality with older rhsm_user
- name: Set deprecated fact for rhel_subscription_user
  set_fact:
    rhsm_user: "{{ rhel_subscription_user }}"
  when: rhel_subscription_user is defined

- name: Set deprecated fact for rhel_subscription_pass
  set_fact:
    rhsm_password: "{{ rhel_subscription_pass }}"
  when: rhel_subscription_pass is defined

- name: Set deprecated fact for rhel_subscription_pool
  set_fact:
    rhsm_pool: "{{ rhel_subscription_pool }}"
  when: rhel_subscription_pool is defined

- name: Add masters to requisite groups
  add_host:
    name: "{{ hostvars[item].inventory_hostname }}"
    groups: allnodes, masters, etcd, nodes, cluster_hosts, master
    openshift_node_group_name: "node-config-master{{
      (openshift_use_crio | bool) | ternary('-crio', '') }}"
  with_items: "{{ groups[cluster_id + '-master'] }}"
  when:
    - "openshift_vers not in ['v3_6', 'v3_7', 'v3_9', 'v3_10']"
- name: Add masters to requisite groups
  add_host:
    name: "{{ hostvars[item].inventory_hostname }}"
    groups: allnodes, masters, etcd, nodes, cluster_hosts, master
    openshift_node_group_name: "node-config-master"
    openshift_node_labels:
      role: master
      node-role.kubernetes.io/master: true
  with_items: "{{ groups[cluster_id + '-master'] }}"
  when:
    - "openshift_vers in ['v3_6', 'v3_7', 'v3_9', 'v3_10']"

- name: Add a master to the single master group
  add_host:
    name: "{{ hostvars[item].inventory_hostname }}"
    groups: single_master
    openshift_node_group_name: "node-config-master{{
      (openshift_use_crio | bool) | ternary('-crio', '') }}"
  with_items: "{{ groups[cluster_id + '-master'][0] }}"
  when:
    - "openshift_vers not in ['v3_6', 'v3_7', 'v3_9', 'v3_10']"
- name: Add a master to the single master group
  add_host:
    name: "{{ hostvars[item].inventory_hostname }}"
    groups: single_master
    openshift_node_group_name: "node-config-master"
    openshift_node_labels:
      role: master
      node-role.kubernetes.io/master: true
  with_items: "{{ groups[cluster_id + '-master'][0] }}"
  when:
    - "openshift_vers in ['v3_6', 'v3_7', 'v3_9', 'v3_10']"

- name: Add compute instances to host group
  add_host:
    name: "{{ hostvars[item].inventory_hostname }}"
    groups: allnodes, nodes, cluster_hosts, schedulable_nodes, compute
    openshift_node_group_name: "node-config-compute{{
      (openshift_use_crio | bool) | ternary('-crio', '') }}"
  with_items: "{{ groups[cluster_id + '-compute'] }}"
  when:
    - "openshift_vers not in ['v3_6', 'v3_7', 'v3_9', 'v3_10']"
- name: Add compute instances to host group
  add_host:
    name: "{{ hostvars[item].inventory_hostname }}"
    groups: allnodes, nodes, cluster_hosts, schedulable_nodes, compute
    openshift_node_group_name: "node-config-compute"
    openshift_node_labels:
      role: compute
      node-role.kubernetes.io/compute: true
      node-role.kubernetes.io/infra: true
  with_items: "{{ groups[cluster_id + '-compute'] }}"
  when:
    - "openshift_vers in ['v3_6', 'v3_7', 'v3_9', 'v3_10']"

- name: Add new node instances to host group
  add_host:
    name: "{{ hostvars[item].inventory_hostname }}"
    groups: allnodes, new_nodes
    openshift_node_group_name: "node-config-compute{{
      (openshift_use_crio | bool) | ternary('-crio', '') }}"
  with_items: "{{ groups.tag_provision_node | default([]) }}"
  when:
    - add_node is defined
    - "openshift_vers not in ['v3_6', 'v3_7', 'v3_9', 'v3_10']"
- name: Add new node instances to host group
  add_host:
    name: "{{ hostvars[item].inventory_hostname }}"
    groups: allnodes, new_nodes
    openshift_node_group_name: "node-config-compute"
    openshift_node_labels:
      role: "{{ node_type }}"
      node-role.kubernetes.io/compute: true
      node-role.kubernetes.io/infra: true
  with_items: "{{ groups.tag_provision_node | default([]) }}"
  when:
    - add_node is defined
    - "openshift_vers in ['v3_6', 'v3_7', 'v3_9', 'v3_10']"

- name: Add cns instances to allnodes
  add_host:
    name: "{{ hostvars[item].inventory_hostname }}"
    groups: allnodes
    openshift_node_group_name: "node-config-storage{{
      (openshift_use_crio | bool) | ternary('-crio', '') }}"
  with_items: "{{ groups[cluster_id + '-storage'] | default([]) }}"

- name: Add crs instances to allnodes
  add_host:
    name: "{{ hostvars[item].inventory_hostname }}"
    groups: allnodes
    openshift_node_group_name: "node-config-storage"
  with_items: "{{ groups[cluster_id + '-crs'] | default([]) }}"

- name: Add cns instances to host group
  add_host:
    name: "{{ hostvars[item].inventory_hostname }}"
    groups: nodes, cluster_hosts, schedulable_nodes, storage
    openshift_node_group_name: "node-config-storage{{
      (openshift_use_crio | bool) | ternary('-crio', '') }}"
  with_items: "{{ groups[cluster_id + '-storage'] }}"
  when:
    - "'cns' in container_storage and add_node is defined and 'storage' in node_type"
    - "openshift_vers not in ['v3_6', 'v3_7', 'v3_9', 'v3_10']"
- name: Add cns instances to host group
  add_host:
    name: "{{ hostvars[item].inventory_hostname }}"
    groups: nodes, cluster_hosts, schedulable_nodes, storage
    openshift_node_labels:
      role: storage
      node-role.kubernetes.io/storage: true
    openshift_node_group_name: "node-config-storage"
  with_items: "{{ groups[cluster_id + '-storage'] }}"
  when:
    - "'cns' in container_storage and add_node is defined and 'storage' in node_type"
    - "openshift_vers in ['v3_6', 'v3_7', 'v3_9', 'v3_10']"

- name: Add crs nodes to the storage group
  add_host:
    name: "{{ hostvars[item].inventory_hostname }}"
    groups: storage, crs
    openshift_node_group_name: "node-config-storage"
  with_items: "{{ groups[cluster_id + '-crs'] }}"
  when:
    - "'crs' in container_storage and add_node is defined and 'storage' in node_type"
